export { default as nationalAssemblyIcon } from "./national-assembly.svg";
export { default as thugAttackIcon } from "./thug-attack-icon.svg";
export { default as robberyIcon } from "./robbery-icon.svg";
export { default as baseFeatureIcon } from "./base-feature-icon.svg";
export { default as baseFeatureIcon2 } from "./base-feature-icon2.svg";
export { default as baseFeatureIcon3 } from "./base-feature-icon3.svg";
export { default as baseFeatureIcon4 } from "./base-feature-icon4.svg";
export { default as baseFeatureIcon5 } from "./base-feature-icon5.svg";
export { default as baseFeatureIcon6 } from "./base-feature-icon6.svg";
export { default as hamburgerIcon } from "./hambuger-icon.svg";
export { default as TrendIcon } from "./trending-up.svg";
export { default as CameraIcon } from "./camera.svg";
export { default as DownloadIcon } from "./downloadIcon.svg";
export { default as ShareIcon} from "./shareIcon.svg";
